CREATE DATABASE IF NOT EXISTS doctor;

USE doctor;

CREATE TABLE IF NOT EXISTS doctors(
id INT AUTO_INCREMENT PRIMARY KEY ,
name VARCHAR(100) NOT NULL,
gender VARCHAR(20) NOT NULL ,
age INT NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
phone VARCHAR(20) NOT NULL,
city VARCHAR(100) NOT NULL ,
institute_name VARCHAR(150) NOT NULL ,
degree_name VARCHAR(150) NOT NULL,
speciality VARCHAR(100) NOT NULL ,
yoe INT NOT NULL,
  consultation_fee DECIMAL(10,2) NOT NULL,
  profile_picture VARCHAR(255),
  search_count INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);